/**
 * Returns true when an email address is suitable for display to the user.
 * Returns false for:
 *  - null / undefined / empty string
 *  - synthetic relay addresses generated by FountainRank (e.g. from social sign-in)
 *  - Apple private relay addresses
 */
export function isDisplayableEmail(email: string | null | undefined): boolean {
  if (!email) return false;
  // Lowercase once so suffix checks are case-insensitive, matching the backend's
  // accept_email normalization.
  const normalized = email.toLowerCase();
  if (normalized.endsWith("@users.noreply.fountainrank.com")) return false;
  if (normalized.endsWith("@privaterelay.appleid.com")) return false;
  return true;
}
